### ISSUE TITLE
Does not take into account newline terminated files

### ISSUE THREAD

**Issue by bharathcs** [Open-Attestation/open-attestation-cli#102]
Taken from [your documentation](https://www.openattestation.com/docs/transferable-record/token-registry), `open-attestation deploy token-registry "Token_Registry" MTR -n ropsten -f key.txt`. However, I have been getting this error:
`✖  error     invalid hexlify value (argument="value", value="0x{...PRIVATE KEY HERE...}\n", code=INVALID_ARGUMENT, version=bytes/5.0.8)`. 
On most text editors (particularly OS X and Linux), the POSIX standard is followed and (see [3.206](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)) all text files terminate with `'\n'`, which causes the bug. Could this command be adjusted to strip the terminating newline character automatically when reading from `key.txt`?

**Comment by bharathcs** [comment]
Quick fix for those who can't find a text editor that lets you save without a terminating newline:
```
(tr -d '\n' < key.txt ) > key_stripped.txt
rm key.txt
mv key_stripped.txt key.txt
```

and then you can carry on with the commands.

**Comment by Nebulis** [comment]
Oh yeah I had the problem once too, I think we could escape it when processing the file

**Comment by Nebulis** [comment]
Could you try if it fixes your problem ?

**Comment by bharathcs** [comment]
Yep, it works now, thanks!
