### ISSUE TITLE
Bug: Exception thrown when wrapping a file without the "issuers" section

### ISSUE THREAD

**Issue by skydudie** [Open-Attestation/open-attestation-cli#126]
When wrapping an .oa file using the FHIR schema, an exception is thrown if the .oa file is missing the "issuers" section.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create raw document conforming to the FHIR schema but leave out the "issuers" section
2. Exception is thrown instead of an error message. See below

**Exception**
![image](https://user-images.githubusercontent.com/28289296/117823125-ba4bb500-b29f-11eb-9eda-c9ff7345bebc.png)

**Expected Error**
![image](https://user-images.githubusercontent.com/28289296/117823257-db140a80-b29f-11eb-9fac-5b74790f4263.png)

**Other Information**
Included a sample of the FHIR document without the issuers section
[Missing Issuer Section.txt](https://github.com/Open-Attestation/open-attestation-cli/files/6459462/Missing.Issuer.Section.txt)

**Comment by Nebulis** [comment]
Hi, I tried with the latest version and it looks like it's fixed. This is what I get:

![image](https://user-images.githubusercontent.com/503185/119313715-73e65500-bca6-11eb-978a-1228b13fe62e.png)

Can you confirm it works for you as well ?

**Comment by cavacado** [comment]
stale closing
