### ISSUE TITLE
Issue while deploying any smart contract, token registry, title-escrow

### ISSUE THREAD

**Issue by Mayur-btc** [Open-Attestation/open-attestation-cli#127]
processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit\"}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x....................
1f55be2a9c8e35f03334a03c2cae283a0efc026fdff72db5deb2ef0077d90ffa055253bbc64a7da4286faa73666fe78da5cd74498b5f8ca70e3b6802cd055d68b\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://ropsten.infura.io/v3/84842078b09946638c03157f83405213", code=SERVER_ERROR, version=web/5.1.0)

I am facing the above problem while running the below command.

open-attestation deploy token-registry "test-123" MTR -n ropsten -f key.txt

1. I have 1ETH in my wallet. 
2. Wallet network is the same as token-registry. like. ropsten.

**Comment by SiaChenRen** [comment]
Hi @Mayur-btc. There seems to have some issues with the Ropsten network last week, could you try to deploy the token registry again? Do inform us again if the issue persists.

**Comment by Mayur-btc** [comment]
> Hi @Mayur-btc. There seems to have some issues with the Ropsten network last week, could you try to deploy the token registry again? Do inform us again if the issue persists.

Hi @SiaChenRen Thank you. Now, Everything working fine now.

**Comment by Mayur-btc** [comment]
Hi @SiaChenRen 

Today, I again face this issue in ropsten network.

replacement fee too low (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\.....code=REPLACEMENT_UNDERPRICED, version=providers/5.1.2)

**Comment by Nebulis** [comment]
Hi, looks like rospten having issues again, it's not something that we have control over
