### ISSUE TITLE
DNS is not valid

### ISSUE THREAD

**Issue by Mayur-btc** [Open-Attestation/open-attestation-cli#132]
I have created the demo DNS to the "Rinkeby" network. I checked in google DNS for my demo DNS and my DNS is there with the TXT record. But when I use this DNS to issue the document on blockchain and try to verify my document, it shows that this DNS is not valid.

I have created the DNS using below command.
open-attestation dns txt-record create --address 0xDBe10687a1F*************385441aC80c --network-id 4

output:
✔  success   Record created at smooth-coral-monkey.sandbox.openattestation.com and will stay valid until Thu May 27 2021 17:56:05 GMT+0530 (India Standard Time)

I am using the "TradeTrust" API to verify the document.
https://api-rinkeby.tradetrust.io/verify
This response is ' "issuerIdentity": false'. 

I have attached DNS result of google.

![Query_ smooth-c](https://user-images.githubusercontent.com/52620062/119662244-cd898380-be4e-11eb-9695-66c42c8a5a5d.png)

Also, I reported issue on TradeTrust Github.
https://github.com/TradeTrust/tradetrust-website/issues/359

**Comment by Nebulis** [comment]
fixed in v1.40.2

**Comment by Mayur-btc** [comment]
Hi @Nebulis ,

I upgrade the version and DNS is working. But I face a problem in creating a "Smart Contract". 
My command:
open-attestation deploy title-escrow -f key.txt -n rinkeby -b 0x9564Ef940CD8*********33b78B8Db23Ac7A7 -h 0x9564Ef940************F33b78B8Db23Ac7A7 -r 0x57CB035C69*****************8D1d02D39abcCB9b

output:
ℹ  info      Deploying title escrow
✖  error     5.0120954111991635e+47 is not a valid Ethereum address

I tried to create a new wallet and new token registry but still face this problem in title-escrow.

open-attestation --version
1.40.2

**Comment by Nebulis** [comment]
please open another issue :)

**Comment by Mayur-btc** [comment]
> please open another issue :). Not sure why you obfuscate part of your command but it's useless, I can retrieve the values from etherscan. Only the private key must be kept secret

Okay. Thanks.
