### ISSUE TITLE
CLI Tool loops when wrapping FHIR Documents

### ISSUE THREAD

**Issue by skydudie** [Open-Attestation/open-attestation-cli#135]
When wrapping an .oa file using the FHIR schema, the CLI Tool enters a loop

**Versions**
CLI Tool: v1.40.2
Schemata: v1.8.6

**To Reproduce**
Steps to reproduce the behaviour:
1. Wrap healthcert-open-attestation-document.json with schema healthcert-open-attestation-schema.json from \src\sg\gov\moh\healthcert\1.0
2. See error below

**Errors**
1. CLI Tool enters a loop
![image](https://user-images.githubusercontent.com/28289296/119783392-bce51600-beff-11eb-917a-977bd49bae85.png)

**Comment by HJunyuan** [comment]
Hi @skydudie, I was unable to replicate this issue on `@govtechsg/open-attestation-cli@1.40.2`.

Here's what works for me:

```bash
# 1. Download sample healthcert-open-attestation-document.json
$ curl https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/1.0/healthcert-open-attestation-document.json --output healthcert-open-attestation-document.json

# 2. Wrap downloaded sample document into ./wrapped/ directory
$ open-attestation wrap healthcert-open-attestation-document.json --output-dir ./wrapped/ --schema https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/1.0/healthcert-open-attestation-schema.json
```

Output:
```bash
{ uri: 'https://schema.openattestation.com/2.0/schema.json' }
{ uri: 'https://schema.openattestation.com/2.0/schema.json' }
{
  uri: 'https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/1.0/schema.json'
}
{
  uri: 'https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/1.0/schema.json'
}
✔  success   Batch Document Root: 0x7b13e0bca08a8ffd6931371929b294f9df1c92115f579e42f7c8439e9c5b99f2
```

**Comment by skydudie** [comment]
Hi @HJunyuan,
I think the issue was resolved when schemata was updated previously
Thanks for checking!
