### ISSUE TITLE
Connecting with alternative networks

### ISSUE THREAD

**Issue by garysyndromes** [Open-Attestation/open-attestation-cli#139]
Hi, are there plans to integrate open-attestation with other networks? asking specifically for polygon network

**Comment by Nebulis** [comment]
Hi :wave: 

We currently have no plans to integrate with another blockchain. However we are open to listen for argument on why open-attestation should support a different blockchain. In addition, we would appreciate if you provide information on how you imagine we should extend open-attestation to support your use case.

I encourage you to discuss about it on the [open-attestation github repository](https://github.com/Open-Attestation/open-attestation/discussions), in the discussions :)
