### ISSUE TITLE
How to run command with proxy settings?

### ISSUE THREAD

**Issue by ngocanhmarine** [Open-Attestation/open-attestation-cli#180]
When I'm using an office computer to integrate TradeTrust to our solution, I have this issue:
I cannot deploy the document-store smart contract to the ropsten network using the command:
open-attestation deploy document-store "My first document store" --network ropsten --encrypted-wallet-path wallet.json
![ảnh](https://user-images.githubusercontent.com/45548370/146873220-435edd72-6abc-4a19-ac66-580f2a0a80f9.png)
The command stopped at "info: Wallet successfully decrypted" without throwing any error.

The office computer has proxy settings, so I tried to set:
set HTTP_PROXY=address:port
set HTTPS_PROXY=address:port
I have tested it by run "curl www.google.com" and it can get the data, which is not able to be done without the above proxy settings.
But when I tried with open-attestation commands, it still not works.

All OA commands that needs to connect to the internet through proxy have this issue: deploy document-store, configuring DNS, wrapping documents, issuing documents.

So my question is, how to run open-attestation commands with proxy settings? 
Can you add feature to config it like: open-attestation deploy document-store "My first document store" --network ropsten --encrypted-wallet-path wallet.json --proxy address:port ?

**Comment by cavacado** [comment]
Hi, thanks for opening this issue.

Unfortunately, this problem can only be resolved at your proxy's configuration side. (There might be certain rules that your proxy forbades, ie connecting to a smart contract, or maybe connecting to infura, without any logs we can only guess)

My suggestion is to map out all network requests you are making then make a request to your network department inorder to whitelist these requests.

Failing that, you can also experiment in a computer without these restrictions first while your request to whitelist some resources continues.

**Comment by ngocanhmarine** [comment]
Hi cavacado,

Thank you for your quick response.
Can you help me to list all the domains that OA commands are requesting to?

**Comment by cavacado** [comment]
Hi there,

I think its much better if you experiment in an unrestricted environment (without proxy connections), put in place a network snooper to trace the calls you are making, then from there create your own custom whitelist to forward to your network department.

**Comment by cavacado** [comment]
stale closing
