### ISSUE TITLE
Documents store issue failed, but didn't show any error message

### ISSUE THREAD

**Issue by 2482103133** [Open-Attestation/open-attestation-cli#184]
It is this what caused this situation?
![image](https://user-images.githubusercontent.com/37145130/148971610-7a9831ec-fe67-426a-af24-3662800fc4a2.png)

**Comment by cavacado** [comment]
Hi thanks for opening an issue:
Could you give more context? environment / network / where the loc is at etc.
- What did you do?
- What did you expect?

**Comment by puayhiang** [comment]
@2482103133 

Thanks for reporting the issue to us, the PR has been merged to main branch.
Do let us know if there's any issue with the fix, otherwise, we will close this issue within the next 3 days.
