### ISSUE TITLE
Does open-attestation-cli support OpenCerts V1 and V2?

### ISSUE THREAD

**Issue by mmysgp** [Open-Attestation/open-attestation-cli#204]
With OpenCerts/certificate-cli,  we can use the following command to specify the OpenCerts schema version:

> node index.js batch **--schema "1.5"** ..\unwrapped_folder ..\wrapped_folder

How can we do so with the open-attestation-cli?  Does it support the wrapping for OpenCerts V1 and V2?

**Comment by HJunyuan** [comment]
Hi @mmysgp, the [open-attestation-cli](https://github.com/Open-Attestation/open-attestation-cli) is only able to work with OpenAttestation V2 and V3 documents.

OpenCerts V2 onwards is built with OpenAttestation. As such, it effectively refers to OpenAttestation V2.

You can see the migration guide here: https://docs.opencerts.io/docs/migrations/v1_to_v2#how-do-i-migrate
Or you can get started from here (it links you to OpenAttestation docs): https://docs.opencerts.io/docs/#starting-with-opencerts
