### ISSUE TITLE
CLI 

### ISSUE THREAD

**Issue by SP-INDT-OpenCert** [Open-Attestation/open-attestation-cli#205]
Hi,

This is more on a question than issue, we've been using certificate-cli for our v2 certs last yr, everything seems to be ok and been verified by the business users. Now I can see that the cli was deprecated, does it mean it will no longer work and we have to switch to open-attestation-cli?

**Comment by HJunyuan** [comment]
Hi @SP-INDT-OpenCert, `certificate-cli` will still work but it would not receive any more updates since it's deprecated. We still strongly recommend to upgrade to `open-attestation-cli` for issuing v2 (or higher) certificates for the best support.
