### ISSUE TITLE
Title escrow creator not found on this network [sepolia, mumbai networks]

### ISSUE THREAD

**Issue by itsarshkalsi** [Open-Attestation/open-attestation-cli#231]
Goerli is failing all transactions at the time, so can you give us the title escrow creator for sepolia, mumbai networks

**Comment by superical** [comment]
Looks like the escrow creator addresses for the 2 networks were missed out. I have added them and published a new release (v1.54.1). Can you update your CLI and try again to see if it works now? Thanks!

**Comment by itsarshkalsi** [comment]
Thanks
