### ISSUE TITLE
wrap: must be able to handle input when input is a file

### ISSUE THREAD

**Issue by Nebulis** [Open-Attestation/open-attestation-cli#26]
## Current Behaviour
`wrap` expect a directory has input. Example from the doc:
```bash
open-attestation wrap ./examples/sample-certs/ ./tmp/wrapped-certs
```

## Expected behaviour
In order to help with w3c compliance, the CLI must be able to handle single file as input. Indeed the W3C vc-test-suite provide a single file as input and not a directory.

## Proposal
```bash
open-attestation wrap ./examples/sample-certs.opencerts ./tmp/wrapped-certs
```

**Comment by benjaminlim00** [comment]
feature completed in https://github.com/Open-Attestation/open-attestation-cli/pull/33
