### ISSUE TITLE
wrap: must be able to write result to stdout

### ISSUE THREAD

**Issue by Nebulis** [Open-Attestation/open-attestation-cli#27]
## Current Behaviour
`wrap` write the result to a directory. Example from the doc:
```bash
open-attestation wrap ./examples/sample-certs/ ./tmp/wrapped-certs
```

## Expected behaviour
In order to help with w3c compliance, the CLI must be able to write the output to stdout. Indeed the W3C vc-test-suite provide a single file, then read stdout and make assertion on the outputted result.

## Proposal
Currently the output dir is a positional argument. This proposal suggest to remove this argument and add options to handle the different use case

### When input is a file (#26)
- using --output-file will write the result to the specified file
- using --output-dir will write the result to the specified directory
- providing no option will write the result to stdout.

```bash
open-attestation wrap ./examples/sample-certs.opencerts --output-file ./path/to/file
```

### When input is a directory
- using --output-dir will write the result to the specified directory (current behaviour)
- other options will throw an error

```bash
open-attestation wrap ./examples/sample-certs/ --output-dir ./path/to/dir
```

**Comment by benjaminlim00** [comment]
completed in https://github.com/Open-Attestation/open-attestation-cli/pulls?q=is%3Apr+is%3Aclosed

Next steps - to change the usage of using signale.disable() in as the method of preventing unwanted console output
