### ISSUE TITLE
wrap: must be able to add a document store to the inputted document(s)

### ISSUE THREAD

**Issue by Nebulis** [Open-Attestation/open-attestation-cli#28]
## Current Behavior
`wrap` expect document to be already correctly formatted

## Expected behavior
In order to help with w3c compliance, the CLI must be able to take in a document store provided as an option, and add the document store to the document(s). Indeed the W3C vc-test-suite provide a single file which doesn't have a document store and which we don't have control on. The best way to handle this is to tell the test suite to provide the document store using the option

## Proposal
This proposal only apply for v3 document and must throw an error when `--oav3` is not provided.
`wrap` will automatically add the document store to the document(s) that must be wrapped.

Considering the following document `./examples/sample-certs.opencerts` as input:
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/58473",
  "type": ["VerifiableCredential", "AlumniCredential"],
  "issuer": "https://example.edu/issuers/14",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "alumniOf": "Example University"
  },
  "proof": {
    "type": "RsaSignature2018"
  }
}
```

running the following command 
```bash
open-attestation wrap ./examples/sample-certs.opencerts ./examples/wrapped --document-store 0xabcd
```

will update the document as follows before wrapping:
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/58473",
  "type": ["VerifiableCredential", "AlumniCredential"],
  "issuer": "https://example.edu/issuers/14",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "alumniOf": "Example University"
  },
  "proof": {
    "type": "RsaSignature2018"
    "method": "DOCUMENT_STORE",
    "value": "0xabcd",
  }
}
```

The transformation will be applied on all the documents, if the input is a directory and not a file.

**Comment by benjaminlim00** [comment]
completed in https://github.com/Open-Attestation/open-attestation-cli/pull/46
