### ISSUE TITLE
location of verification service for test certs

### ISSUE THREAD

**Issue by wmclaxton** [Open-Attestation/open-attestation-cli#310]
All along, we have been using https://dev.opencerts.io for verifying certificates which are issued on the testnet.  We are seeing a 403 error at that location.  Has that location changed?

**Comment by HJunyuan** [comment]
@wmclaxton I am able to confirm that `https://dev.opencerts.io/` is still accessible from my end. In order to diagnose this issue, may I know which region or IP address you are accessing from?

**Comment by wmclaxton** [comment]
Hmm... My IP is 209.0.7.134 (https://whatismyipaddress.com/ip/209.0.7.134).  I am currently in Arizona USA and am not using any VPN.

**Comment by wmclaxton** [comment]
I am able to work around this by making a VPN connection to Singapore.  You may close the issue.
