### ISSUE TITLE
Do you have API to topup production Ethereum wallet?

### ISSUE THREAD

**Issue by HDBISG** [Open-Attestation/open-attestation-cli#88]
Hello, 

May I ask do you have Node JS API to topup production Ethereum wallet?

Regards,
ZhangJi

**Comment by Nebulis** [comment]
As of today no, how would you like to topup ? transfer from another wallet ?

**Comment by HDBISG** [comment]
If I don't topup wallet, I can't deploy document store and can't issue document. so need to topup wallet first.

**Comment by Nebulis** [comment]
You can buy from a service and transfer to your wallet => https://geek.sg/blog/complete-guide-to-buying-bitcoin-ethereum-or-other-cryptocurrencies-in-singapore

We don't provide such service
