### ISSUE TITLE
Do you support issue verifiable and transferable document javascript API?

### ISSUE THREAD

**Issue by HDBISG** [Open-Attestation/open-attestation-cli#89]
Hello,

Thank you support wrap document API at https://openattestation.com/docs/component/open-attestation

May I ask do you support issue verifiable and transferable document javascript API?

Regards,
ZJ

**Comment by Nebulis** [comment]
- https://github.com/Open-Attestation/open-attestation-cli#issue
- https://github.com/Open-Attestation/open-attestation-cli#issue-1

**Comment by HDBISG** [comment]
This is issue command, I need Javascript API of issue document

**Comment by Nebulis** [comment]
You can check the code of this repo. For instance this => https://github.com/Open-Attestation/open-attestation-cli/blob/master/src/implementations/document-store/issue.ts#L34

**Comment by HDBISG** [comment]
Noded, thanks.
