### ISSUE TITLE
Do you support javascript API to change Owner and Holder?

### ISSUE THREAD

**Issue by HDBISG** [Open-Attestation/open-attestation-cli#90]
Hello,

I can change Owner and Holder at UI page: https://dev.tradetrust.io/viewer 
May I ask do you support javascript API to change Owner and Holder?

Regards,
ZJ

**Comment by Nebulis** [comment]
@dhemutton :)

**Comment by dhemutton** [comment]
Hi, may I know what do you mean by javascript API? We are currently using a hook to access the function to change owner and holder here https://github.com/TradeTrust/tradetrust-website/blob/master/src/common/contexts/TokenInformationContext/TokenInformationContext.tsx#L95

**Comment by HDBISG** [comment]
Thanks reply!
The [Wrapper SDK (javascript)](https://openattestation.com/docs/component/open-attestation) is very good.
Do we have the javascript API to change Owner or Shipper document like Wrapper SDK (javascript)?

**Comment by dhemutton** [comment]
Currently we don't have an API for that yet but we will work on that soon😊! Thanks for bringing it up!

**Comment by HDBISG** [comment]
Thank you for planning to do that API!

**Comment by dhemutton** [comment]
**However if you need it urgently:**
If you're using React, you can get the TitleEscrow through this 
```
const instance = TitleEscrowFactory.connect(titleEscrowAddress, provider); 
setTitleEscrow(instance);
```
before initiating your change of owner and holder through the useContract hook through this
```
const { send: changeHolder, state: changeHolderState, reset: resetChangeHolder } = useContractFunctionHook(
    titleEscrow,
    "changeHolder"
  );
```
If you're using oa-cli, you can change the method [here](https://github.com/Open-Attestation/open-attestation-cli/blob/master/src/implementations/document-store/issue.ts#L34). Replace DocumentStoreFactory with TitleEscrowFactory and replace issue with changeOwner. Hope it helps!

**Comment by HDBISG** [comment]
Thank you very much! 
Let me read these codes.

**Comment by cavacado** [comment]
stale closing
