### ISSUE TITLE
How to configure both document store address and token registry address with 1 DNS

### ISSUE THREAD

**Issue by HDBISG** [Open-Attestation/open-attestation-cli#92]
I have a document store address and a token registry address, but I only have 1 DNS domain name.
How to configure both document store address and token registry address with 1 DNS?

**Comment by Nebulis** [comment]
you can add as many dns-txt entries as you want, there is no limitations on that. just add them separately, each entries surrounded by double quotes:

```
"openatts net=ethereum netId=1 addr=0xabcd"
"openatts net=ethereum netId=1 addr=0x1234"
```

**Comment by HDBISG** [comment]
Greate!
Thanks, let me try.
